### PR TITLE
Add rules for 2-arg assert without tree transform

### PR DESCRIPTION
**Pull request by rocky**
It seems we were missing grammar rules for the two arg assert. 

I think we should have both options, since both are valid. 

I note that for the 1-arg assert parsing does pick that up, but arbitrarily decides to go with the `if` instead.

### CODE REVIEW

**Comment by x0ret** [comment]
With having following diff:

```diff
diff --git a/decompyle3/scanners/scanner3.py b/decompyle3/scanners/scanner3.py
index 5a874110..cf752a03 100644
--- a/decompyle3/scanners/scanner3.py
+++ b/decompyle3/scanners/scanner3.py
@@ -263,7 +263,9 @@ class Scanner3(Scanner):
                     next_inst.opname == "LOAD_GLOBAL"
                     and next_inst.argval == "AssertionError"
                 ):
-                    if i + 2 < n and self.insts[i + 2].opname.startswith(
+                    raise_idx = self.offset2inst_index[inst.argval - 2]
+                    raise_inst = self.insts[raise_idx]
+                    if raise_inst.opname.startswith(
                         "RAISE_VARARGS"
                     ):
                         self.load_asserts.add(next_inst.offset)
```

We are handling `LOAD_ASSERT` for 2-arg-assert, `assert2` rule needs change, am i correct?

Besides we can have this fix in this branch.

**Comment by rocky** [comment]
> We are handling LOAD_ASSERT for 2-arg-assert, assert2 rule needs change, am i correct?

I am not sure I understand the question, but let me describe the situation as I see it. In the master branch, we don't have grammar rule for nonterminal `assert2`. There was one in the Python 2.6 grammar which is now being made use of in the branch as a tree transformation. In the `assert2` branch I added the missing rule (but it would need slight adjustment when some `LOAD_GLOBAL`s becomes `LOAD_ASSERT`s). 

So the change to `scanner3.py` should go into that branch, it gets merged into master, and then we'll rebase this branch. 

To be explicit about how I see things, I do not see any problem having assert2 fixed both by adding the grammar rule and by having it be a tree transformation as well. In my opinion this is good because it adds _robustness_ to the code. Individually each is correct. 

In the parser when several grammar rules match one is selected and although I suppose this is deterministic (it will happen the same way each time), it is not easy to figure out which of several rules will be selected. Adding other rules can change things. 

In the past, such as in `uncompyle2`, I think there was an effort to jigger the parse rules to try to force the "better" way to be selected. This causes complexity and requires mysterious voodoo incantations that I don't think anybody fully understands. It is just the way it is because that seems to work. 

 Now that there is a tree-transformation phase, we don't have to rely on such magical incantations. Instead we describe rules that are correct. And there is another phase that is changing things when this is not the most pleasing way to present things. 

I need to write some of this down somewhere else, but here is also the bigger picture. As we've seen things can be handled in a number of different places in a couple of different ways. Such as here in handling 2-arg asserts. However each phase does have its focus and specialty. 

In parsing we are primarily trying to recognize patterns and sort out the incorrect piecing together of patterns from the correct one. 

In the tree transformation phase the focus is a little different in that what we start out is a correct tree translation and when we finish we still have a correct tree translation. Ideally we are not trying to detect errors like we are in parsing. And its focus is in doing the tree translation is to make things look nicer. Right now (before DRYing duplicate code) this phase is optional.

**Comment by x0ret** [comment]
Thanks for the explanation. 

The question was exactly what you stated.

> (but it would need slight adjustment when some LOAD_GLOBALs becomes LOAD_ASSERTs)

We have `LOAD_GLOBAL` since as you said: 

> @x0ret By the way that LOAD_ASSERT is in fact LOAD_GLOBAL in 3.7, but perhaps the "ingest" should look for that and change the LOAD_GLOBAL to ``LOAD_ASSERT`.

`scanner3.py` fails when it's detecting `LOAD_GLOBAL AssertaionError` and converting to `LOAD_ASSERT`. The diff i provided above fixes this as i suppose. Finally when `scanner3.py` provides true `LOAD_ASSERT`s i think we can change the rule you committed as follows:
```
        assert2 ::= assert_expr jmp_true LOAD_GLOBAL LOAD_STR
                    CALL_FUNCTION_1 RAISE_VARARGS_1 COME_FROM
``` 

To this (?):

```        
assert2 ::= assert_expr jmp_true LOAD_ASSERT LOAD_STR
                    CALL_FUNCTION_1 RAISE_VARARGS_1 COME_FROM
```
Sorry for unclear question.

**Comment by x0ret** [comment]
Besides do we need a grammer for something like this ? 
```python
assert x, print('msg')
```

with bytecodes: 
```
   5      36  LOAD_NAME                'x'
          38  POP_JUMP_IF_TRUE     52  'to 52'
          40  LOAD_GLOBAL              'AssertionError'
          42  LOAD_NAME                'print'
          44  LOAD_STR                 'msg'
          46  CALL_FUNCTION         1
          48  CALL_FUNCTION         1
          50  RAISE_VARARGS_1       1
```

And maybe we can have this grammer instead:

```
        assert2 ::= assert_expr jmp_true LOAD_ASSERT expr
                     RAISE_VARARGS_1 COME_FROM
```

**Comment by rocky** [comment]
> And maybe we can have this grammar instead:
>
>        assert2 ::= assert_expr jmp_true LOAD_ASSERT expr
>                    RAISE_VARARGS_1 COME_FROM

Yes this is better - thanks. This kind of problem/situation happens a lot but I think it is (largely) unavoidable. You see a pattern so you make the smallest rule that matches it. Then you discover there is another situation and the two can be combined easily into a broader pattern. 

When you write the rule you don't want to be too general before encountering a particular situation. 

However the two ways to avoid this is to do like you have done in the past and come up with lots of examples of 2-arg assert. The other possibility is to check the rule against Python grammar to see if there is a more general situation here. Sorry I haven't done either of these two things.

**Comment by x0ret** [comment]
Please let me know if it is not the commit you wanted.

**Comment by rocky** [comment]
@x0ret In testing this, it seems that the `LOAD_STRING` can be replaced by `expr` but the`CALL_FUNCTION_1` has to remain. 

See the changed tests for confirmation. 

Yes, this is tricky stuff.

**Pull request merged**
