### PR TITLE
Try out Python blacken reformatter

### PR DESCRIPTION
**Pull request by rocky**
@x0ret  Here is the code reformatted using the python reformatter [blacken](https://black.readthedocs.io/en/stable/). 

Your thoughts and comments?

### CODE REVIEW

**Comment by x0ret** [comment]
This is cool, seems to be good for diffing. Thanks.

(Can we have a prioritized TODO list (for these projects) ? )

**Comment by rocky** [comment]
Will work on prioritized list.

**Comment by rocky** [comment]
@x0ret See if https://github.com/rocky/python-decompile3#workspaces/python-bytecode-decompilation-5d0531e6693682482417e0f0/board?repos=47907821,94722771,187480317 does it. 

The highest priority items are the hardest and will take the longest. 

Feel free to add and reorder as you see fit.

**Comment by x0ret** [comment]
Thanks, but the link redirects me to `python-decompile3` repo home page. Am i missing something?

**Comment by rocky** [comment]
This stuff is new to me (too). I created I guess a zenhub "workspace" so 
Python-bytecode-decompilation

Next to "rocky/python-decompile3" should the  "workspace" name "Python Bytecode Decompilation" which I think if you click on will get you to this zenhub thing. If you have another or preferred way to give priorities, let me know.

**Comment by x0ret** [comment]
Thanks for the screenshot, i didn't have ZenHub enabled. And i have the access now. Thanks again.

**Pull request merged**
