### PR TITLE
http://github.com/rocky/python-uncompyle6/pull/273

### PR DESCRIPTION
**Pull request by rocky**
with removal of code not related to 3.7+

@x0ret  Please review to see I haven't botched anything. 

After this I may just reformat the changed files here and maybe in uncompyle6 as well.

### CODE REVIEW

**Comment by x0ret** [comment]
Thanks for handling this.

@rocky In my testing specially in uncompyle6, I observed all `mk_func` (including annotated ones) cases for `3.6+` is handled by `make_function3` instead of `make_function3_annotate` which is for `<= 3.5`.

Please consider following case:

```python
class BoundedSemaphore(Semaphore):
    def __init__(self, value: int=1, *, loop: 'q'=None) -> int:
        super().__init__(value, loop=loop)
```

and we have this tree in decompile3:
```
          function_def (2)
                 0. mkfunc (7)
                     0. expr
                        L.  10       8  LOAD_CONST               (1,)
                     1. expr
                        dict (3)
                             0. expr
                                            10  LOAD_CONST               None
                             1.             12  LOAD_CONST               ('loop',)
                             2.             14  BUILD_CONST_KEY_MAP_1     1
                     2. expr
                        dict (5)
                             0. expr
                                            16  LOAD_NAME                int
                             1. expr
                                            18  LOAD_STR                 'q'
                             2. expr
                                            20  LOAD_NAME                int
                             3.             22  LOAD_CONST               ('value', 'loop', 'return')
                             4.             24  BUILD_CONST_KEY_MAP_3     3
```
Do we need `make_function3_annotate` here?

**Comment by rocky** [comment]
Yes, I think so. If you know what to do and it is easy to do, feel free to add on to this PR.

**Comment by x0ret** [comment]
Although i have a working patch, however i'm not sure about all cases, Please continue on merging this and i will send PR later when i came to a fully working and tested situation. Thanks.

**Comment by rocky** [comment]
Ok.

**Comment by rocky** [comment]
@x0ret  I've just reformtted some of the files with blacken. So in your outstanding changes use that reformatter too and the diffs will come out small.

**Pull request merged**
