### PR TITLE
Move docstring detection to tree transform

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by rocky** [comment]
One little thing I noticed is that I am not seeing the docstring node when I show the tree. At some point we probably will need to figure out how to show everything in a sane fasion.

**Comment by x0ret** [comment]
> One little thing I noticed is that I am not seeing the docstring node when I show the tree. At some point we probably will need to figure out how to show everything in a sane fashion.

As far as i review the code, we only show the ast before perfoming transform phase. Do you prefer having both AST? Or adding another option for showing the transformed AST? Please let me know what you prefer and i will implement the case.

**Comment by rocky** [comment]
Here is what I think would be ideal. Option for before, option for after, option to indicate transformations summary (e.g  `assert` transformation done on tree, `elif` transformation done on tree.)

What do you think?

**Comment by x0ret** [comment]
@rocky, Please comment on this so i can push the changes.

According to your comment, i implemented this test feature as follows:
1. `--tree` now requires a val of set `{=before, =after, =summary}`
2. `summary` gives us the following sample output: 
```python
# decompyle3 version 3.3.2
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.3 (default, May 13 2019, 14:49:41)
# [Clang 10.0.1 (clang-1001.0.46.4)]
# Embedded file name: simple_source/bug36/00_if_elif.py
# Size of source mod 2**32: 296 bytes

assert transformation done on tree
elif transformation done on tree

def testit(b):
    if b == 1:
        a = 1
    elif b == 2:
        a = 2
    else:
        a = 4
    return a


for x in (1, 2, 4):
    x = testit(x)
    assert x is not None, 'Should have returned a value, not None'
    assert x == x
# okay decompiling ../python-decompile3/test/bytecode_3.7_run/00_if_elif.pyc
``` 

3. `before` stands for showing AST before transformations and `after` for showing AST after transformations.

My comments:

1. Maybe `summary` is not accurate in this option since i think it's not related to AST? Maybe a better option? 
2. Can we localized the `maybe_show_tree` for `TreeTransform` and `SourceWalker`? Since handling `before,after` needs a check for e.g. `isinstanse(...)` or a flag to check the caller. What's your opinion?
3. I used `self.maybe_show_summary("assert")` for showing the summary. This was just an idea and i'd be grateful to have your comment on this. Maybe a better way?

Anyway I'd be grateful to hear and follow your experienced suggestions about the implementation.

Thank you

**Comment by x0ret** [comment]
Also about last `docstring` case which is placed in `build_class` i observed that we can use transformation on two phase:
1. When `n_classdef` is executed but this seems to need more work.
2. When `build_ast` is executed in `build_class` which is easier but needs an inefficient (?) work (Iterating all self.ast in `TreeTransform.treetransform` for checking docstring).

I implement the second case for now and we have following tree (Please note we get two `docstring` node there):
```
stmts (4)
     0. sstmt
        stmt
            assign (2)
                 0. expr
                    L.   1       0  LOAD_NAME                __name__
                 1. store
                                 2  STORE_NAME               __module__
     1. sstmt
        stmt
            assign (2)
                 0. expr
                                 4  LOAD_STR                 'A'
                 1. store
                                 6  STORE_NAME               __qualname__
     2. docstring
                     0  LOAD_STR                 '\n    BBBB\n    '
     3. sstmt
        stmt
            function_def (2)
                 0. mkfunc (4)
                     0. L.   5      12  LOAD_CODE                <code_object B>
                     1.             14  LOAD_STR                 'A.B'
                     2. docstring
                                    -1  LOAD_STR                 '\n        CCC\n        '
                     3.             16  MAKE_FUNCTION_0          ''
                 1. store
                                18  STORE_NAME               B
``` 

for this test case:

```
class A():
    """
    BBBB
    """
    def B(self):
        """
        CCC
        """
        pass
```

What do you think? However i'm truly ready for implementing the first case, Please let me know what you prefer.

**Comment by rocky** [comment]
> `--tree now requires a val of set {=before, =after, =summary}`

This is great! Can I combine options, e.g. `--tree=before,after` or `--tree=before --tree=summary` ?

> summary gives us the following sample output:

The output is good too. However it would be nice to list in which functions (or lack of functions if this is in the main module) where the transformations occurred to give some sense of where this is. Location could also be given by bytecode offset, or original source code line, although the original source code line is going to be hardest for people to understand where we are talking about.

Note though that we don't need transformation information about adding docstrings since that happens all the time.

I just remembered another place which should be handled in the tree transformation phase...

Bytecode in functions (at least for some versions of Python) always ends with some sort of `RETURN` instruction which translates of course into a Python `return` statement. However convention is not to add `return None` to most functions. And we even see something like (in pseudo bytecode assembly): 

```
RETURN 2
RETURN None
```

so clearly the last instruction is not helpful since it is never reached.

Currenltly the decompilers do remove this. But this should be done in the tree transform phase rather than `pysource.py` as is done now.

This was too difficult for me to try to tackle initially. If you are up for that, please investigate and fix. 


> Maybe summary is not accurate in this option since i think it's not related to AST?

Another suggestion is `transform`. By the way, I know we keep talking about this as an AST, and that's how spark-parser refers to it it but the "A" for "Abstract" is part isn't so. Initially all instructions are represented, so in that sence it is not abstract. It is however a syntax tree. The transformation phase however does open the possibility that this can be abstracted more. For example it could be possible to remove nodes that aren't used in triggering in the source-code output. However note in the fragment version we do want all instructions to be kept because we query by bytecode offset.

> Can we localized the maybe_show_tree for TreeTransform and SourceWalker? Since handling before,after needs a check for e.g. isinstanse(...) or a flag to check the caller. What's your opinion?

My opinion is that when you do the work you should be offered a lot of freedom to explore ideas and do things as it best pleases you. This project especially is different than `uncompyle6` because right now no one depends on it.

We haven't even put out the first formal release!

Right now I am thinking of dong that after we get the control flow thing worked out better, or if it is really needed for 3.8 and we don't want to cram a lot of stuff into `uncompyle6` for that.  So please make this more like you home kind of project and go wild!


>  (Please note we get two docstring node there):

I see to _different_ docstrings and that's how it should be since they are distinct. I don't see the same thing repeated. To start out, just do as you feel is best or expedient. This is already an improvement, and right now I'm just looking for improvements. Down the line we can fix up as we understand how to do things better.

The one thing that I do note that looks funny to me is having the docstring under `sstmts` be somewhere in the middle (2) between two `sstmt`s. I can understand it being ether at the beginning or the end (the beginning seems to be most natural because that's how it is in the source text), but if for whatever reason putting it at the end makes things easier to code, so be it.

I looked at Python's AST to see if there was something we could do to make that match. Nope, Python's AST doesn't seem to have a slot in its AST for a docstring. However...

I did come across [`ast.getdocstring(node)`(https://docs.python.org/3/library/ast.html#ast.get_docstring). That requires an Python AST node, but I wonder if there is code from that we could either call or copy if it is too hard to call directly. 

> However i'm truly ready for implementing the first case, Please let me know what you prefer.

If you are up for implementing, please do. Of course I, probably like you, want the best thing. I am more pragmatic rather than fascist about it though. 

> EDIT: Do you have a test case for this line. I failed to find such a case.

I can't think of one off hand. Recall though that this comes from `uncompyle6` so it might be done in versions of Python that aren't handled by `decompyle3`.

Finally, please do commit what you have either in this branch or make a new one if you want off of this one. It is easier for me to understand things when I can see and try real code.

Thanks, and thanks for all of the great work!

**Comment by rocky** [comment]
@x0ret had another thought instead of or in addition to  summary info on transformation.  There could be a mark in a node that indicates it was created as a result of a transformation. Then when showing the tree after transformation, just seeing the mark would probably be enough to indicate what happened.

**Comment by x0ret** [comment]
> Can I combine options, e.g. --tree=before,after or --tree=before --tree=summary ?

Yes, we supports the later now.

> However it would be nice to list in which functions (or lack of functions if this is in the main module) where the transformations occurred to give some sense of where this is. 

We supports this too now.

> Note though that we don't need transformation information about adding docstrings since that happens all the time.

Unfortunately, we supports this now, i'm going to remove this in the next revision.

> Currenltly the decompilers do remove this. But this should be done in the tree transform phase rather than pysource.py as is done now.

I think we have this in the new commit, Please fix me if i'm wrong.

> The one thing that I do note that looks funny to me is having the docstring under sstmts be somewhere in the middle (2) between two sstmts. I can understand it being ether at the beginning or the end

We have docstring in the beginning now (not true for `n_mkfunc`).

> If you are up for implementing, please do. Of course I, probably like you, want the best thing. I am more pragmatic rather than fascist about it though.

In this commit i didn't implement, I will revised.

> Finally, please do commit what you have either in this branch or make a new one if you want off of this one. It is easier for me to understand things when I can see and try real code.

Sure.

> @x0ret had another thought instead of or in addition to summary info on transformation. There could be a mark in a node that indicates it was created as a result of a transformation. Then when showing the tree after transformation, just seeing the mark would probably be enough to indicate what happened.

We supports this now. Following is an example of doing such in a tree after transformation (`--tree=after`):

```
     3. sstmt
        stmt
            function_def (2)
                 0. mkfunc (4) (transformed by n_mkfunc)
                     0. L.   5      12  LOAD_CODE                <code_object B>
                     1.             14  LOAD_STR                 'A.B'
                     2. docstring (transformed by n_mkfunc)
                                    -1  LOAD_STR                 '\n        CCC\n        '
                     3.             16  MAKE_FUNCTION_0          ''
                 1. store
                                18  STORE_NAME               B
```

**Comment by rocky** [comment]
```
3. sstmt
        stmt
            function_def (2)
                 0. mkfunc (4) (transformed by n_mkfunc)
                     0. L.   5      12  LOAD_CODE                <code_object B>
                     1.             14  LOAD_STR                 'A.B'
                     2. docstring (transformed by n_mkfunc)
                                    -1  LOAD_STR                 '\n        CCC\n        '
                     3.             16  MAKE_FUNCTION_0          ''
                 1. store
                                18  STORE_NAME               B
```

I love it! (As well as the rest...)

**Comment by rocky** [comment]
> I had another thought instead of or in addition to summary info on transformation. There could be a mark in a node that indicates it was created as a result of a transformation. Then when showing the tree after transformation, just seeing the mark would probably be enough to indicate what happened.

Yes that is just as good.

**Comment by rocky** [comment]
@x0ret in 40e34c7f I added a couple of tweaks.  Using `-T` with optoin `--tree=after` was causing an error since there aren't templates in the transformation phase. And I made a stab at  updating `--help`. I hope you don't mind. Feel free to add to this or adjust. 

In trying there were two things I noticed. If you use both `--tree=after` and `--tree=before` it can be confusing because you need to infer where the before ends and the after begins. It would be nice to make that more clear somehow. 

The other thing noticed is that the templates are given in the "before" phase when logically it feels like it should be given after tree transformation. 

I had been also thinking that if the message were put inside `template_engine` we'd catch more cases such as when we start out with a `n_xxx` procedure and then in that call `self.template_engine()` instead of `self.default()`.

What do you think?

**Comment by x0ret** [comment]
> @x0ret in 40e34c7 I added a couple of tweaks. Using -T with option --tree=after was causing an error since there aren't templates in the transformation phase. And I made a stab at updating --help. I hope you don't mind. Feel free to add to this or adjust.

I appreciate it.

> In trying there were two things I noticed. If you use both --tree=after and --tree=before it can be confusing because you need to infer where the before ends and the after begins. It would be nice to make that more clear somehow.

I assume you are talking about separating two part? If so i think we can have a separator when the next one begins. 

> The other thing noticed is that the templates are given in the "before" phase when logically it feels like it should be given after tree transformation.

Let me try migrating templates to tree transformation.

> I had been also thinking that if the message were put inside template_engine we'd catch more cases such as when we start out with a n_xxx procedure and then in that call self.template_engine() instead of self.default().

Could you please explain it a bit more? Honestly, i'm not in the context enough.

**Comment by rocky** [comment]
> I assume you are talking about separating two part? If so i think we can have a separator when the next one begins.

Yes, sorry. I meant separating the two parts. A separator line of some sort would be fine. I wanted to try point out the problem without restricting you to a specific solution, e.g. a separator line consisting of `=` or `-` or whatever, because you might have other ideas or have a preference on what looks best.

> Let me try migrating templates to tree transformation.

Let me clarify what I meant. Here is an excerpt of a run: 

```
./bin/decompyle3 -T --tree=before --tree=after test/bytecode_3.7_run/00_if_elif.pyc
# decompyle3 version 3.3.2
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.3 (default, Mar 28 2019, 19:44:41) 
# [GCC 7.3.0]
# Embedded file name: simple_source/bug36/00_if_elif.py
# Size of source mod 2**32: 296 bytes
stmts (2)
     0. sstmt
        stmt
            function_def (2): ('\n\n%|def %c\n', -2)
                 0. mkfunc (3)
                     0. L.   2       0  LOAD_CODE                <code_object testit>
                     1.              2  LOAD_STR                 'testit'
                     2.              4  MAKE_FUNCTION_0          ''
                 1. store
                                 6  STORE_NAME               testit
     1. sstmt
     ...
                         1. lastl_stmt
                            assert (4) (transformed by n_ifstmt)
                                 0. assert_expr
     ....     

stmts (2)
     0. sstmt
        stmt
            function_def (2)
                 0. mkfunc (3)
                     0. L.   2       0  LOAD_CODE                <code_object testit>
                     1.              2  LOAD_STR                 'testit'
                     2.              4  MAKE_FUNCTION_0          ''
                 1. store
                                 6  STORE_NAME               testit
```

leaving aside the making a separation between the two parts, "after" comes before "before" and that is confusing.

As for template in the tree transformation phase, I'd also like to clarify: `template_engine()` of `pysource.py` is about transforming a tree fragment into a string fragment which gets collected. There is a slightly extended version of `template_engine()` in `fragments.py` because that needs to do a little more and so the patterns there need to be extended a little.

In both cases the intent or idea was to write a DSL (domain-specific language) to shorten the tedium coding the same kinds of things over and over again. In other words the language expresses what needs to be done succinctly. _As a side benefit,_  it helps in the debug output to show what has going on, better than just saying, "hey, I called this procedure here".

I don't think we could create a DSL for tree transformation kinds of things _without having first written it out in long hand first done_. So in that sense, not having one now doesn't seem to be a burden, given there isn't that much code.

But sure if you want to abstract what's there to make all the `if` ... `elif` ugliness go away, and reduce code in the other functions, go at it.

But to be clear, I was _not_ thinking of is taking `template_engine` of `pysource.py` and moving largely as is to `transform.py`. I like the fact that transform.py has no notion of output and that makes it simpler. At about 230 lines, `transform.py` is pretty short. I also like after removing tree transformation stuff from `pysource.py` it is now at a more manageable size at 2300 lines (which is still a lot be less than it was).


> Could you please explain it a bit more? Honestly, i'm not in the context enough.

I am sorry I wasn't clear. Right now `str_with_template1()` shows the template. This is good, but it misses calls to `template_engine()` in `n_yield()`, `n_dict()` or `print_super_classes3()`, among other places. If the debug check were in `template_engine()`, then we would show more transformations in the syntax tree display.


Note that last function mentioned function, `print_super_classes3()` is a little different from the other in that it is called from `n_classdef()` and doesn't contain everything that is printed. So there might be an optional flag in the call and display to indicate this is only _part_ of what was printed.

Lastly, a delayed response to something earlier in this thread

> > Currenltly the decompilers do remove this. But this should be done in the tree transform phase rather than pysource.py as is done now.

> I think we have this in the new commit, Please fix me if i'm wrong.

As I look over `pysource.py` I see this:

```
    def is_return_none(self, node):
        # Is there a better way?
        ret = (
            node[0] == "ret_expr"
            and node[0][0] == "expr"
            and node[0][0][0] == "LOAD_CONST"
            and node[0][0][0].pattr is None
        )
        if self.version <= 2.6:
            return ret
        else:
            # FIXME: should the SyntaxTree expression be folded into
            # the global RETURN_NONE constant?
            return ret or node == SyntaxTree(
                "return", [SyntaxTree("ret_expr", [NONE]), Token("RETURN_VALUE")]
            )
```

This is purely a tree transformation kind of thing, even if it is only to _remove_ the node. This and whatever is making use of it should then be moved.

Thanks for doing all of this.

**Comment by rocky** [comment]
@x0ret I had a little bit of time today, so I started making some of the changes I suggested. Please review and make changes as you see fit.

One thing I have come to realize is that the transformation in `n_mkfunc` should really just be part of the grammar and then no transformation is needed. 

In general I think we want to do as much in the grammar as possible, while transformations are for those things that can't easily be done by the grammar. For `mkfunc` the custom rule would just refer to the docstring rule at the right place in the rule.

**Comment by rocky** [comment]
@x0ret one other thing I notiiced and that the changes move towards. Having the showast dictionary structure in retrospect is a little bit overkill at least for the tree transform phase. For that all you need is a boolean to show the tree or not. For the to-string transformation the two options are to show the tree and whether or not to include the template info. 6

Here's why... Showing the _after_  the transform phase is the same as showing the to-string transform phase. And clearly we don't need to print these twice. So it suffices I thiink to assume the transform phase means "before".  And in the to-string phase "before" and "after" are the same thing.

In sum, as an `decompyle3` options, "before" and "after" have specific meanings, but within a phase, they dont.

**Comment by rocky** [comment]
@x0ret let's merge and fix up whatever remains down the line. Overall I really really like this and would love to see it appear in `uncompyle6`.

**Pull request merged**
